name: Request PR review
run-name: ${{ github.actor }} created a new PR  ${{ github.event.url }} 🚀
on:
  pull_request:
    types: [ ready_for_review ]
jobs:
  Request-PR-Review:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/workflows/code-review
    steps:
      - run: node codeReview.js --user ${{ github.actor }} --pr ${{ github.event.url }}
